---
# Certbot setup
- name: Create certificate directory for ubuntu user
  file:
    path: "{{ paths.certs }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  become: yes

- name: Copy cert files in loop
  copy:
    src: "/etc/letsencrypt/live/{{ domains.masterserver }}/{{ item }}"
    dest: "{{ paths.certs }}/{{ item }}"
    remote_src: yes
    owner: ubuntu
    group: ubuntu
    mode: '0600'
  loop:
    - fullchain.pem
    - privkey.pem
  become: yes
  ignore_errors: yes
  notify: restart masterserver

- name: Create certbot renewal hook directory
  file:
    path: /etc/letsencrypt/renewal-hooks/deploy
    state: directory
    mode: '0755'
  become: yes

- name: Install certbot renewal hook
  template:
    src: ../templates/copy-certs.sh.j2
    dest: /etc/letsencrypt/renewal-hooks/deploy/copy-certs.sh
    mode: '0755'
  become: yes

- name: Enable certbot renewal timer
  systemd:
    name: certbot.timer
    enabled: yes
    state: started
  become: yes
