---
# Restart serwerÃ³w (masterserver + gameserver)
- name: Restart Hypersomnia Servers
  hosts: web_servers
  gather_facts: no

  tasks:
    - name: Restart masterserver
      systemd:
        name: masterserver
        state: restarted
      become: yes
      tags: [masterserver]

    - name: Restart gameserver
      systemd:
        name: hypersomnia
        state: restarted
      become: yes
      tags: [gameserver]
